# Generated by Django 6.1rc1 on 2026-09-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_alter_recipe_category_alter_recipe_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveIntegerField(default=1, help_text="В минутах"),
            preserve_default=False,
        ),
    ]
